-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.device_by_deveui(IN lookup_dev_eui text)
    RETURNS device
    LANGUAGE 'plpgsql' STABLE 
    PARALLEL UNSAFE
    COST 100
    
AS $BODY$
declare
  dev record;
begin
  select *
  into strict dev
  from device
  where lower(device.dev_eui) = lower(lookup_dev_eui);

  return dev;

  exception
    when no_data_found then
        raise exception 'Device with DEV_EUI "%" not found', lookup_dev_eui;
end
$BODY$;
