-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.get_device(
	deveui text)
    RETURNS device
    LANGUAGE 'plpgsql'
    COST 100
    STABLE
AS $BODY$
declare
    rec record;
begin
    select *
    into strict rec
    from device
    where lower(dev_eui) = lower(deveui);
    return rec;
    exception
        when no_data_found then
            raise exception 'Device % not found', eui;

END
$BODY$;

ALTER FUNCTION public.get_device(text)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.get_device(text) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.get_device(text) TO anon;

GRANT EXECUTE ON FUNCTION public.get_device(text) TO authenticated;

GRANT EXECUTE ON FUNCTION public.get_device(text) TO postgres;

GRANT EXECUTE ON FUNCTION public.get_device(text) TO service_role;
