# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
    - main
    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout@v2
      
jobs:
  ci:
    env:
      TTS_COMMUNITY_API_KEY: ${{ secrets.TTS_COMMUNITY_API_KEY }}
      SUPABASE_PUBLIC_ANON_KEY: ${{ secrets.SUPABASE_PUBLIC_ANON_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SECRET_JWT: ${{ secrets.SUPABASE_SECRET_JWT }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MAPBOX_ACCESS_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17.6]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache pnpm modules
      uses: actions/cache@v2
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-

    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.26.1 
        run_install: |
          - recursive: true
            
    - name: Test
      run: pnpm test -r 
      
    - name: Lint
      run: pnpm lint -r
      
    - name: Build
      run: pnpm build
